//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAJAX.UI.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurkeyCities
    {
        public byte ID { get; set; }
        public string CityName { get; set; }
        public Nullable<long> CriminalCount { get; set; }
        public Nullable<long> Param1 { get; set; }
    
        public virtual OtherTable OtherTable { get; set; }
    }
}
